# Generated by Django 4.2.2 on 2023-06-19 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('release_film', models.DateTimeField(null=True)),
                ('rating', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.films')),
            ],
        ),
    ]
