# Generated by Django 4.2.2 on 2023-06-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('second_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('release_film', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actors', models.ManyToManyField(blank=True, to='polls.actor')),
                ('country', models.ManyToManyField(to='polls.country')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.director')),
                ('genres', models.ManyToManyField(to='polls.genre')),
            ],
        ),
    ]
