# Generated by Django 4.2.2 on 2023-06-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_image_name_films_film_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='film_id',
            new_name='film',
        ),
    ]
