# Generated by Django 4.2.7 on 2023-11-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name": "Актёры", "verbose_name_plural": "Актёры"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Страны", "verbose_name_plural": "Страны"},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"verbose_name": "Режиссеры", "verbose_name_plural": "Режиссеры"},
        ),
        migrations.AlterModelOptions(
            name="films",
            options={
                "ordering": ["id"],
                "verbose_name": "Фильмы",
                "verbose_name_plural": "Фильмы",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанры", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Баннеры", "verbose_name_plural": "Баннеры"},
        ),
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя и Фамилия"),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="director",
            name="first_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="director",
            name="second_name",
            field=models.CharField(max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="films",
            name="actors",
            field=models.ManyToManyField(
                blank=True, to="polls.actor", verbose_name="Актеры"
            ),
        ),
        migrations.AlterField(
            model_name="films",
            name="country",
            field=models.ManyToManyField(to="polls.country", verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="films",
            name="description",
            field=models.CharField(max_length=500, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="films",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.director",
                verbose_name="Режиссер",
            ),
        ),
        migrations.AlterField(
            model_name="films",
            name="genres",
            field=models.ManyToManyField(to="polls.genre", verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="films",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="films",
            name="rating",
            field=models.FloatField(blank=True, null=True, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="films",
            name="release_film",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Дата выхода"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(max_length=50, verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="image",
            name="film",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.films",
                verbose_name="Фильм",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Баннер"),
        ),
        migrations.CreateModel(
            name="HistoricalFilms",
            fields=[
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "release_film",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Дата выхода"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="Рейтинг"),
                ),
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="polls.director",
                        verbose_name="Режиссер",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Фильмы",
                "verbose_name_plural": "historical Фильмы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
