# Generated by Django 4.2.2 on 2023-06-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_actor_alter_films_release_film_director_films_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='second_name',
        ),
        migrations.AddField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 19, 11, 15, 6, 396800)),
        ),
    ]
