# Generated by Django 4.2.2 on 2023-06-19 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_name_director_second_name_director_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 19, 11, 27, 5, 81280)),
        ),
    ]
