# Generated by Django 4.2.2 on 2023-06-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_films_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='film',
        ),
        migrations.AddField(
            model_name='image',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.films'),
        ),
    ]
