# Generated by Django 4.2.2 on 2023-06-19 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_first_name_actor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 19, 11, 37, 36, 438203)),
        ),
    ]
