# Generated by Django 4.2.2 on 2023-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
