# Generated by Django 4.2.2 on 2023-06-19 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_films_release_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 19, 11, 40, 28, 156825)),
        ),
    ]
