# Generated by Django 4.2.2 on 2023-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_films_release_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
