# Generated by Django 4.2.2 on 2023-06-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_films_release_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.director'),
        ),
    ]
