# Generated by Django 4.2.2 on 2023-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_country_films_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='country',
        ),
        migrations.AddField(
            model_name='films',
            name='country',
            field=models.ManyToManyField(to='polls.country'),
        ),
    ]
