# Generated by Django 4.2.2 on 2023-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_films_country_films_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='films',
            name='genres',
        ),
        migrations.AddField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(to='polls.genre'),
        ),
    ]
