# Generated by Django 4.2.2 on 2023-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_genre_remove_films_genres_films_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
