# Generated by Django 4.2.2 on 2023-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_films_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
