# Generated by Django 4.2.2 on 2023-06-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_films_release_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='actors',
            field=models.ManyToManyField(blank=True, to='polls.actor'),
        ),
        migrations.AlterField(
            model_name='films',
            name='country',
            field=models.ManyToManyField(blank=True, to='polls.country'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.director'),
        ),
        migrations.AlterField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(blank=True, to='polls.genre'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
