# Generated by Django 4.2.2 on 2023-06-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_films_actors_alter_films_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.director'),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
