# Generated by Django 4.2.2 on 2023-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_films_director_alter_films_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='country',
            field=models.ManyToManyField(to='polls.country'),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(to='polls.genre'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='films',
            name='release_film',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
